import { int, mysqlEnum, mysqlTable, text, timestamp, varchar, decimal, json, uniqueIndex, index } from "drizzle-orm/mysql-core";

export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(), openId: varchar("openId", { length: 64 }).notNull().unique(), name: text("name"), email: varchar("email", { length: 320 }), loginMethod: varchar("loginMethod", { length: 64 }), role: mysqlEnum("role", ["user", "admin", "qa", "scientist"]).default("user").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(), lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export const lots = mysqlTable("lots", { id: int("id").autoincrement().primaryKey(), lotCode: varchar("lotCode", { length: 64 }).notNull().unique(), deviceFamily: varchar("deviceFamily", { length: 100 }).notNull(), dataLabel: varchar("dataLabel", { length: 100 }).notNull().default("Synthetic / Demonstration Data"), specificationMax: decimal("specificationMax", { precision: 12, scale: 4 }).notNull(), safetyMargin: decimal("safetyMargin", { precision: 12, scale: 4 }).notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() }, t => ({ lotCodeIdx: uniqueIndex("lot_code_idx").on(t.lotCode) }));
export const components = mysqlTable("components", { id: int("id").autoincrement().primaryKey(), componentCode: varchar("componentCode", { length: 64 }).notNull().unique(), lotId: int("lotId").notNull().references(() => lots.id), scenario: varchar("scenario", { length: 80 }).notNull(), unit: varchar("unit", { length: 20 }).notNull().default("µA"), createdAt: timestamp("createdAt").defaultNow().notNull() }, t => ({ lotIdx: index("component_lot_idx").on(t.lotId) }));
export const measurements = mysqlTable("measurements", { id: int("id").autoincrement().primaryKey(), componentId: int("componentId").notNull().references(() => components.id), checkpointHours: int("checkpointHours").notNull(), leakageCurrent: decimal("leakageCurrent", { precision: 12, scale: 4 }).notNull(), temperatureC: decimal("temperatureC", { precision: 8, scale: 3 }).notNull().default("25"), voltageV: decimal("voltageV", { precision: 8, scale: 3 }).notNull().default("5"), measuredAt: timestamp("measuredAt").defaultNow().notNull() }, t => ({ componentTimeIdx: uniqueIndex("component_time_idx").on(t.componentId, t.checkpointHours) }));
export const analysisRuns = mysqlTable("analysis_runs", { id: int("id").autoincrement().primaryKey(), componentId: int("componentId").notNull().references(() => components.id), status: varchar("status", { length: 30 }).notNull(), resultJson: json("resultJson").notNull(), modelVersion: varchar("modelVersion", { length: 60 }).notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() }, t => ({ analysisComponentIdx: index("analysis_component_idx").on(t.componentId) }));
export const investigations = mysqlTable("investigations", { id: int("id").autoincrement().primaryKey(), componentId: int("componentId").notNull().references(() => components.id), status: mysqlEnum("status", ["OPEN", "CLOSED"]).notNull().default("OPEN"), suggestedAction: varchar("suggestedAction", { length: 80 }).notNull(), openedBy: int("openedBy").references(() => users.id), createdAt: timestamp("createdAt").defaultNow().notNull(), closedAt: timestamp("closedAt") });
export const decisions = mysqlTable("decisions", { id: int("id").autoincrement().primaryKey(), investigationId: int("investigationId").notNull().references(() => investigations.id), decision: varchar("decision", { length: 80 }).notNull(), comment: text("comment"), decidedBy: int("decidedBy").references(() => users.id), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const auditLogs = mysqlTable("audit_logs", { id: int("id").autoincrement().primaryKey(), action: varchar("action", { length: 80 }).notNull(), targetType: varchar("targetType", { length: 50 }).notNull(), targetId: varchar("targetId", { length: 80 }), actorId: int("actorId").references(() => users.id), metadataJson: json("metadataJson"), createdAt: timestamp("createdAt").defaultNow().notNull() }, t => ({ auditTimeIdx: index("audit_time_idx").on(t.createdAt) }));
export const modelVersions = mysqlTable("model_versions", { id: int("id").autoincrement().primaryKey(), name: varchar("name", { length: 80 }).notNull(), modelType: varchar("modelType", { length: 80 }).notNull(), version: varchar("version", { length: 40 }).notNull(), featureVersion: varchar("featureVersion", { length: 40 }).notNull(), datasetId: varchar("datasetId", { length: 120 }).notNull(), metricsJson: json("metricsJson").notNull(), trainedAt: timestamp("trainedAt").defaultNow().notNull() });
export const deviceFamilies = mysqlTable("device_families", { id: int("id").autoincrement().primaryKey(), familyCode: varchar("familyCode", { length: 80 }).notNull().unique(), description: text("description"), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const testRuns = mysqlTable("test_runs", { id: int("id").autoincrement().primaryKey(), lotId: int("lotId").notNull().references(() => lots.id), runCode: varchar("runCode", { length: 80 }).notNull().unique(), conditionJson: json("conditionJson"), startedAt: timestamp("startedAt").defaultNow().notNull() });
export const driftPredictions = mysqlTable("drift_predictions", { id: int("id").autoincrement().primaryKey(), componentId: int("componentId").notNull().references(() => components.id), analysisId: int("analysisId").notNull().references(() => analysisRuns.id), horizonHours: int("horizonHours").notNull(), predictedValue: decimal("predictedValue", { precision: 12, scale: 4 }).notNull(), lowerBound: decimal("lowerBound", { precision: 12, scale: 4 }), upperBound: decimal("upperBound", { precision: 12, scale: 4 }), modelVersion: varchar("modelVersion", { length: 60 }).notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const riskScores = mysqlTable("risk_scores", { id: int("id").autoincrement().primaryKey(), componentId: int("componentId").notNull().references(() => components.id), analysisId: int("analysisId").notNull().references(() => analysisRuns.id), score: decimal("score", { precision: 6, scale: 2 }).notNull(), band: varchar("band", { length: 30 }).notNull(), contributorsJson: json("contributorsJson").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;
export type Lot = typeof lots.$inferSelect;
export type Component = typeof components.$inferSelect;
export type Measurement = typeof measurements.$inferSelect;
export type AnalysisRun = typeof analysisRuns.$inferSelect;
