import { useEffect, useMemo, useState } from "react";
import { Activity, CheckCircle2, FlaskConical, Gauge, Play, ShieldAlert } from "lucide-react";
import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { isDemoPreview } from "@/const";
import { useAuth } from "@/_core/hooks/useAuth";
import { Area, AreaChart, CartesianGrid, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { toast } from "sonner";

const challengeScenarios = ["Static PASS / Dynamic Anomaly", "Accelerating Drift", "Common-Cause Shift", "High Uncertainty", "False Positive Candidate"];

export default function AnalysisPipeline() {
  const { user, loading } = useAuth();
  const canRead = Boolean(user) || isDemoPreview();
  const components = trpc.components.list.useQuery(undefined, { enabled: canRead, retry: 1 });
  const models = trpc.models.list.useQuery(undefined, { enabled: canRead, retry: 1 });
  const [selectedId, setSelectedId] = useState<number>();
  const selected = useMemo(() => components.data?.find(component => component.id === selectedId), [components.data, selectedId]);
  const detail = trpc.components.get.useQuery({ id: selectedId! }, { enabled: canRead && !!selectedId, retry: 1 });
  const run = trpc.analysis.run.useMutation({ onSuccess: () => { detail.refetch(); toast.success("Analysis recomputed from persisted measurements"); }, onError: error => toast.error(error.message) });
  useEffect(() => { if (!selectedId && components.data?.length) setSelectedId(components.data.find(component => component.scenario === challengeScenarios[0])?.id ?? components.data[0].id); }, [components.data, selectedId]);
  const chartData = (detail.data?.measurements ?? []).map(measurement => ({ time: `${measurement.checkpointHours}h`, measured: Number(measurement.leakageCurrent) }));
  const analysis = detail.data?.result;

  return <DashboardLayout><div className="container space-y-6 pb-12">
    {!canRead && !loading ? <Card className="blueprint-panel"><CardContent className="p-8 text-center"><p className="font-medium">Sign in to load the analysis pipeline.</p><p className="mt-2 text-sm text-muted-foreground">No protected API request is made until a session is available.</p></CardContent></Card> : null}
    <header className="flex flex-col gap-4 border-b border-border pb-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="blueprint-label text-indigo-300">PIPELINE / COMPUTED EVIDENCE</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Analysis Pipeline</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Challenge scenarios execute through the same persisted analysis path used by the primary SIH demonstration. No prerecorded analytical outputs are used.</p></div><div className="flex w-full flex-col gap-2 sm:w-auto sm:flex-row"><Select value={String(selectedId ?? "")} onValueChange={value => setSelectedId(Number(value))}><SelectTrigger className="w-full sm:w-[260px]"><SelectValue placeholder="Select scenario" /></SelectTrigger><SelectContent>{components.data?.filter(component => challengeScenarios.includes(component.scenario)).map(component => <SelectItem key={component.id} value={String(component.id)}>{component.scenario}</SelectItem>)}</SelectContent></Select><Button onClick={() => selectedId && run.mutate({ componentId: selectedId })} disabled={!selectedId || run.isPending}><Play className="mr-2 h-4 w-4" />{run.isPending ? "Computing…" : "Run analysis"}</Button></div></header>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{challengeScenarios.map(scenario => { const match = components.data?.find(component => component.scenario === scenario); return <button key={scenario} onClick={() => match && setSelectedId(match.id)} className={`rounded-xl border p-4 text-left transition-colors hover:border-indigo-400/60 ${match?.id === selectedId ? "border-indigo-400 bg-indigo-400/10" : "border-border bg-card"}`}><div className="flex items-center justify-between gap-2"><span className="text-xs font-semibold uppercase tracking-[.12em] text-muted-foreground">Scenario {challengeScenarios.indexOf(scenario) + 1}</span><FlaskConical className="h-4 w-4 text-indigo-300" /></div><p className="mt-3 text-sm font-medium">{scenario}</p><p className="mt-2 text-xs text-muted-foreground">{match ? match.componentCode : "Unavailable"}</p></button>; })}</section>
    {!analysis ? <Card className="blueprint-panel"><CardContent className="grid min-h-[300px] place-items-center p-8 text-center"><div><Gauge className="mx-auto h-8 w-8 text-indigo-300" /><p className="mt-3 font-medium">Select a live scenario to inspect computed evidence.</p><p className="mt-1 text-sm text-muted-foreground">The pipeline uses measured checkpoints, lot peers, uncertainty, and safety rules from the database.</p></div></CardContent></Card> : <>
      <section className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><Card className="blueprint-panel"><CardHeader><CardTitle className="flex items-center gap-2 text-sm"><Activity className="h-4 w-4 text-indigo-300" />Computed pipeline output</CardTitle></CardHeader><CardContent className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[{label:"Static", value:analysis.staticResult}, {label:"Dynamic", value:analysis.dynamicResult}, {label:"168h forecast", value:analysis.predicted168h == null ? "—" : `${analysis.predicted168h.toFixed(2)} µA`}, {label:"Risk", value:analysis.riskScore == null ? "—" : `${analysis.riskScore.toFixed(1)} / 100`}].map(item => <div key={item.label} className="rounded-lg border border-border bg-background/60 p-3"><p className="blueprint-label">{item.label}</p><p className="mt-2 break-words font-mono text-sm font-semibold">{item.value}</p></div>)}</CardContent></Card><Card className="blueprint-panel"><CardHeader><CardTitle className="flex items-center gap-2 text-sm"><ShieldAlert className="h-4 w-4 text-indigo-300" />Uncertainty and boundary</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><div className="flex justify-between gap-3"><span className="text-muted-foreground">Prediction interval</span><span className="font-mono">{analysis.predictionInterval ? `${analysis.predictionInterval[0].toFixed(1)}–${analysis.predictionInterval[1].toFixed(1)} µA` : "Unavailable"}</span></div><div className="flex justify-between gap-3"><span className="text-muted-foreground">Uncertainty level</span><Badge variant="outline">{analysis.uncertaintyLevel}</Badge></div><div className="flex justify-between gap-3"><span className="text-muted-foreground">Safety boundary</span><span className="font-mono">{analysis.safetyBoundary?.toFixed(2) ?? "—"} µA</span></div><div className="flex justify-between gap-3"><span className="text-muted-foreground">Boundary margin</span><span className="font-mono">{analysis.boundaryMargin?.toFixed(2) ?? "—"} µA</span></div></CardContent></Card></section>
      <Card className="blueprint-panel"><CardHeader><CardTitle className="text-sm">Measured trajectory and safety boundary</CardTitle></CardHeader><CardContent><div className="h-[300px] min-h-[240px] w-full min-w-0"><ResponsiveContainer width="100%" height="100%" minWidth={1} minHeight={240}><AreaChart data={chartData}><defs><linearGradient id="pipelineArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#818cf8" stopOpacity={0.45} /><stop offset="100%" stopColor="#818cf8" stopOpacity={0.02} /></linearGradient></defs><CartesianGrid stroke="var(--border)" vertical={false} /><XAxis dataKey="time" stroke="var(--muted-foreground)" fontSize={11} /><YAxis stroke="var(--muted-foreground)" fontSize={11} /><Tooltip contentStyle={{ background: "var(--popover)", border: "1px solid var(--border)", color: "var(--popover-foreground)" }} /><Area type="monotone" dataKey="measured" stroke="#818cf8" fill="url(#pipelineArea)" strokeWidth={2} /><ReferenceLine y={analysis.safetyBoundary} stroke="#f59e0b" strokeDasharray="5 5" label={{ value: "Safety boundary", fill: "#fbbf24", fontSize: 11 }} /></AreaChart></ResponsiveContainer></div></CardContent></Card>
    </>}
    <Card className="blueprint-panel"><CardHeader><CardTitle className="flex items-center gap-2 text-sm"><CheckCircle2 className="h-4 w-4 text-indigo-300" />Model evaluation view</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{(models.data ?? []).map(model => <div key={model.id} className="rounded-lg border border-border bg-background/60 p-4"><p className="text-sm font-medium">{model.name}</p><p className="mt-1 text-xs text-muted-foreground">{model.version} · {model.featureVersion}</p><div className="mt-4 grid grid-cols-3 gap-2 text-center text-xs"><div><p className="text-muted-foreground">MAE</p><p className="mt-1 font-mono">{(model.metricsJson as { mae?: number })?.mae ?? "—"}</p></div><div><p className="text-muted-foreground">RMSE</p><p className="mt-1 font-mono">{(model.metricsJson as { rmse?: number })?.rmse ?? "—"}</p></div><div><p className="text-muted-foreground">R²</p><p className="mt-1 font-mono">{(model.metricsJson as { r2?: number })?.r2 ?? "—"}</p></div></div></div>)}{!models.data?.length && <p className="text-sm text-muted-foreground">Model metadata will appear after the demonstration dataset is initialized.</p>}</CardContent></Card>
  </div></DashboardLayout>;
}
