import { TRPCError } from "@trpc/server";
import { z } from "zod";
import { COOKIE_NAME } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { protectedProcedure, publicProcedure, router } from "./_core/trpc";
import { validateCsv } from "./reliability";
import { ensureDemoDataset, getLots, getLot, getComponents, getComponent, getMeasurements, getLatestAnalysis, getLatestAnalyses, computeComponentAnalysis, createInvestigation, closeInvestigation, getAuditLogs, getInvestigations, getDecisions, getModels, recordAudit, updateUserProfile, listUsers, updateUserRole } from "./db";

const decisionSchema = z.enum(["Accept", "Hold", "Re-test", "Extend Burn-In", "Reject", "Investigate Further"]);
export const roleGuard = (role: string) => role === "admin" || role === "qa";
const scientistGuard = (role: string) => role === "admin" || role === "scientist" || role === "user";
export const adminGuard = (role: string) => role === "admin";
export const isDemoPreviewRequest = (req: { headers: Record<string, unknown> }) => req.headers["x-vanguard-preview"] === "demo";
const scientistProcedure = protectedProcedure.use(({ ctx, next }) => scientistGuard(ctx.user.role) ? next() : Promise.reject(new TRPCError({ code: "FORBIDDEN", message: "Scientist / Reliability Engineer role required" })));
const qaProcedure = protectedProcedure.use(({ ctx, next }) => roleGuard(ctx.user.role) ? next() : Promise.reject(new TRPCError({ code: "FORBIDDEN", message: "QA Engineer role required" })));
const adminProcedure = protectedProcedure.use(({ ctx, next }) => adminGuard(ctx.user.role) ? next() : Promise.reject(new TRPCError({ code: "FORBIDDEN", message: "Admin role required" })));
const readProcedure = publicProcedure.use(({ ctx, next }) => ctx.user || isDemoPreviewRequest(ctx.req) ? next() : Promise.reject(new TRPCError({ code: "UNAUTHORIZED", message: "Authentication required" })));

export const appRouter = router({
  system: systemRouter,
  auth: router({ me: publicProcedure.query(async opts => { if (opts.ctx.user) await recordAudit("LOGIN_SESSION_OBSERVED", "user", String(opts.ctx.user.id), opts.ctx.user.id); return opts.ctx.user; }), updateProfile: protectedProcedure.input(z.object({ name: z.string().trim().min(2).max(120), email: z.string().trim().email().max(320) })).mutation(async ({ input, ctx }) => { const user = await updateUserProfile(ctx.user.openId, input); if (!user) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Profile could not be saved" }); await recordAudit("PROFILE_UPDATED", "user", String(ctx.user.id), ctx.user.id, { fields: ["name", "email"] }); return user; }), logout: publicProcedure.mutation(({ ctx }) => { const cookieOptions = getSessionCookieOptions(ctx.req); ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 }); return { success: true } as const; }) }),
  admin: router({ users: adminProcedure.query(() => listUsers()), updateUserRole: adminProcedure.input(z.object({ id: z.number().int().positive(), role: z.enum(["user", "admin", "qa", "scientist"]) })).mutation(async ({ input, ctx }) => { const updated = await updateUserRole(input.id, input.role); if (!updated) throw new TRPCError({ code: "NOT_FOUND", message: "User not found" }); await recordAudit("USER_ROLE_UPDATED", "user", String(input.id), ctx.user.id, { role: input.role }); return updated; }) }),
  ingestion: router({ validate: scientistProcedure.input(z.object({ csv: z.string().min(1).max(50000000), filename: z.string().max(200).optional() })).mutation(async ({ input, ctx }) => { const report = validateCsv(input.csv); await recordAudit("DATASET_VALIDATED", "dataset", input.filename ?? "inline-csv", ctx.user.id, { valid: report.valid, rowCount: report.rowCount, errorCount: report.errors.length }); return report; }) }),
    dashboard: router({
    summary: readProcedure.query(async () => { await ensureDemoDataset(); const lots = await getLots(); const comps = await getComponents(); const latestRows = await getLatestAnalyses(comps.map(c => c.id)); const latestByComponent = new Map(latestRows.map(row => [row.componentId, row])); const analyses = await Promise.all(comps.map(async component => { const lot = lots.find(candidate => candidate.id === component.lotId); if (!lot) return null; const latest = latestByComponent.get(component.id); if (latest) return { component, lot, measurements: [], result: latest.resultJson as Awaited<ReturnType<typeof computeComponentAnalysis>>["result"] }; try { return await computeComponentAnalysis(component.id, false); } catch { return null; } })); const valid = analyses.filter(Boolean) as Awaited<ReturnType<typeof computeComponentAnalysis>>[]; const highRisk = valid.filter(a => (a.result.riskScore ?? 0) >= 61).length; const critical = valid.filter(a => (a.result.riskScore ?? 0) >= 81).length; const anomalies = valid.filter(a => a.result.dynamicResult === "ANOMALOUS").length; return { totalComponents: comps.length, totalLots: lots.length, highRisk, critical, anomalyRate: comps.length ? Math.round(anomalies / comps.length * 100) : 0, lotHealth: lots.map(lot => { const inLot = valid.filter(a => a.component.lotId === lot.id); const avgRisk = inLot.length ? inLot.reduce((sum, a) => sum + (a.result.riskScore ?? 0), 0) / inLot.length : 0; return { ...lot, avgRisk: Math.round(avgRisk * 10) / 10, componentCount: inLot.length, anomalyCount: inLot.filter(a => a.result.dynamicResult === "ANOMALOUS").length }; }), recentInvestigations: await getInvestigations(), syntheticLabel: "Synthetic / Demonstration Data" }; }),
  }),
  lots: router({ list: readProcedure.query(async () => { await ensureDemoDataset(); return getLots(); }), get: readProcedure.input(z.object({ id: z.number().int() })).query(async ({ input }) => { await ensureDemoDataset(); const lot = await getLot(input.id); if (!lot) throw new TRPCError({ code: "NOT_FOUND", message: "Lot not found" }); const components = await getComponents(input.id); return { lot, components }; }) }),
  components: router({ list: readProcedure.input(z.object({ lotId: z.number().int().optional() }).optional()).query(async ({ input }) => { await ensureDemoDataset(); return getComponents(input?.lotId); }), get: readProcedure.input(z.object({ id: z.number().int() })).query(async ({ input }) => { await ensureDemoDataset(); const result = await computeComponentAnalysis(input.id); const investigations = (await getInvestigations()).filter(i => i.componentId === input.id); const investigationHistory = await Promise.all(investigations.map(async i => ({ ...i, decisions: await getDecisions(i.id) }))); return { ...result, investigations: investigationHistory }; }) }),
  analysis: router({ run: scientistProcedure.input(z.object({ componentId: z.number().int() })).mutation(async ({ input, ctx }) => { await ensureDemoDataset(); const result = await computeComponentAnalysis(input.componentId); await recordAudit("ANALYSIS_EXECUTED", "component", String(input.componentId), ctx.user.id, { modelVersion: result.result.modelVersion, riskScore: result.result.riskScore }); await recordAudit("RECOMMENDATION_GENERATED", "component", String(input.componentId), ctx.user.id, { suggestedAction: result.result.suggestedAction }); return result; }), get: readProcedure.input(z.object({ componentId: z.number().int() })).query(async ({ input }) => getLatestAnalysis(input.componentId)) }),
  predictions: router({ get: readProcedure.input(z.object({ componentId: z.number().int() })).query(async ({ input }) => (await computeComponentAnalysis(input.componentId)).result) }),
  explanations: router({ get: readProcedure.input(z.object({ componentId: z.number().int() })).query(async ({ input }) => { const result = await computeComponentAnalysis(input.componentId); return { evidence: result.result.evidence, featureContributions: result.result.featureContributions, caveat: "Feature contribution indicates model influence, not proven physical causation." }; }) }),
  investigations: router({ list: readProcedure.query(() => getInvestigations()), create: scientistProcedure.input(z.object({ componentId: z.number().int() })).mutation(async ({ input, ctx }) => { await ensureDemoDataset(); const analysis = await computeComponentAnalysis(input.componentId); return createInvestigation(input.componentId, analysis.result.suggestedAction, ctx.user.id); }), get: readProcedure.input(z.object({ id: z.number().int() })).query(async ({ input }) => ({ id: input.id, decisions: await getDecisions(input.id) })), decide: qaProcedure.input(z.object({ investigationId: z.number().int(), decision: decisionSchema, comment: z.string().max(1000).optional() })).mutation(async ({ input, ctx }) => { if (!roleGuard(ctx.user.role)) throw new TRPCError({ code: "FORBIDDEN", message: "QA role required" }); return closeInvestigation(input.investigationId, input.decision, input.comment, ctx.user.id); }) }),
  audit: router({ list: readProcedure.query(() => getAuditLogs()) }),
  configuration: router({ updateBoundary: adminProcedure.input(z.object({ lotId: z.number().int(), safetyBoundary: z.number().positive().max(100000) })).mutation(async ({ input, ctx }) => { await recordAudit("CONFIGURATION_CHANGED", "lot", String(input.lotId), ctx.user.id, { safetyBoundary: input.safetyBoundary }); return { recorded: true, ...input }; }) }),
  models: router({ list: readProcedure.query(async ({ ctx }) => { await ensureDemoDataset(); const models = await getModels(); if (ctx.user) await recordAudit("MODEL_METADATA_REVIEWED", "model", models[0]?.version, ctx.user.id, { count: models.length }); return models; }) }),
});
export type AppRouter = typeof appRouter;
