import { Activity, ArrowRight, ClipboardCheck, Database, FileSearch, Settings2, ShieldCheck, Users } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { setDemoRole, type DemoRole } from "@/const";

type Role = "admin" | "qa" | "scientist" | "user";

const roleCopy: Record<Role, { eyebrow: string; title: string; description: string; actions: { label: string; detail: string; href: string; icon: typeof Activity }[] }> = {
  admin: { eyebrow: "ADMIN / OPERATIONS COMMAND", title: "Govern the reliability workspace.", description: "Monitor system health, controlled configuration, user access, and the audit trail from one administrative command surface.", actions: [{ label: "Configuration", detail: "Manage safety boundaries and controlled changes.", href: "/configuration", icon: Settings2 }, { label: "User management", detail: "Assign Admin, Scientist, and QA workspace roles.", href: "/admin/users", icon: Users }, { label: "Audit activity", detail: "Review recent decisions and system events.", href: "/investigations", icon: ShieldCheck }] },
  scientist: { eyebrow: "SCIENTIST / RELIABILITY ENGINEER", title: "Turn signals into defensible evidence.", description: "Start with component risk, run the computed pipeline, and open investigations when observed behavior diverges from expectation.", actions: [{ label: "Reliability control", detail: "Inspect components, lots, and risk decomposition.", href: "/reliability", icon: Activity }, { label: "Analysis pipeline", detail: "Run scenario analysis with uncertainty bounds.", href: "/analysis", icon: Database }, { label: "Investigation queue", detail: "Open and track evidence-led investigations.", href: "/investigations", icon: FileSearch }] },
  user: { eyebrow: "SCIENTIST / RELIABILITY ENGINEER", title: "Turn signals into defensible evidence.", description: "Start with component risk, run the computed pipeline, and open investigations when observed behavior diverges from expectation.", actions: [{ label: "Reliability control", detail: "Inspect components, lots, and risk decomposition.", href: "/reliability", icon: Activity }, { label: "Analysis pipeline", detail: "Run scenario analysis with uncertainty bounds.", href: "/analysis", icon: Database }, { label: "Investigation queue", detail: "Open and track evidence-led investigations.", href: "/investigations", icon: FileSearch }] },
  qa: { eyebrow: "QA ENGINEER / DECISION REVIEW", title: "Close the loop with accountable QA decisions.", description: "Review flagged components, inspect the evidence trail, and record the final screening decision with rationale.", actions: [{ label: "Investigation queue", detail: "Prioritize open evidence review items.", href: "/investigations", icon: ClipboardCheck }, { label: "Reliability control", detail: "Inspect the underlying component evidence.", href: "/reliability", icon: Activity }, { label: "Analysis pipeline", detail: "Review model output and uncertainty.", href: "/analysis", icon: Database }] },
};

export default function RoleDashboard({ role, demoPreview = false }: { role: Role; demoPreview?: boolean }) {
  const copy = roleCopy[role];
  return <Card className="blueprint-panel overflow-hidden"><CardHeader className="border-b border-border bg-indigo-500/[0.04] pb-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="blueprint-label text-indigo-300">{copy.eyebrow}</p><CardTitle className="mt-2 text-xl">{copy.title}</CardTitle><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">{copy.description}</p></div><Badge variant="outline" className="w-fit border-indigo-400/30 text-indigo-300">{demoPreview ? "Read-only preview" : role === "admin" ? "Admin workspace" : role === "qa" ? "QA workspace" : "Research workspace"}</Badge></div>{demoPreview && <div className="mt-4 flex flex-wrap items-center gap-2 border-t border-border pt-3"><span className="mr-1 text-[10px] font-semibold uppercase tracking-[.14em] text-muted-foreground">Test accounts</span>{(["admin", "scientist", "qa"] as DemoRole[]).map(testRole => <button key={testRole} onClick={() => { setDemoRole(testRole); window.location.reload(); }} className={`rounded-md border px-2.5 py-1.5 text-xs font-medium transition-colors ${role === testRole ? "border-indigo-400 bg-indigo-400/15 text-indigo-200" : "border-border text-muted-foreground hover:bg-accent hover:text-foreground"}`}>{testRole === "admin" ? "Admin" : testRole === "scientist" ? "Scientist" : "QA Engineer"}</button>)}</div>}</CardHeader><CardContent className="grid gap-3 p-4 md:grid-cols-3">{copy.actions.map(action => <a key={action.href} href={action.href} className="group rounded-lg border border-border bg-background/50 p-4 transition-colors hover:border-indigo-400/50 hover:bg-indigo-400/[0.06]"><div className="flex items-center justify-between gap-3"><action.icon className="h-4 w-4 text-indigo-300" /><ArrowRight className="h-4 w-4 text-muted-foreground transition-transform group-hover:translate-x-1" /></div><p className="mt-4 text-sm font-semibold">{action.label}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{action.detail}</p></a>)}</CardContent></Card>;
}
